server:
  port: 10000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: swagger
          uri: http://localhost:${server.port} #포워딩할 주소, lb://{yureka에 등록한 서비스이름}
          predicates:
            - Path=/v3/api-docs/** #해당 리소스로 들어오면 위에 uri로 보내겠다는 조건
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

        - id: tuna
          uri: http://localhost:12000
          #uri: lb://info-service
          predicates:
            - Path=/tuna/**
          #filters:
          #  - RewritePath=/info/(?<path>.*), /$\{path}

        - id: tunaEclass
          uri: http://localhost:12001
          #uri: lb://info-service
          predicates:
            - Path=/tunaEclass/**
          #filters:
          #  - RewritePath=/info/(?<path>.*), /$\{path}

        - id: tunaLectureApply
          uri: http://localhost:12002
          #uri: lb://cm-service
          predicates:
            - Path=/tunaLectureApply/**
          #filters:
          #  - RewritePath=/cm/(?<path>.*), /$\{path}


