server:
  port: 12000

spring:
  mvc:
    servlet:
      path: /tuna
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
  config:
    activate:
      on-profile: common

springdoc:
  gateway-url: http://localhost:10000
