

server:
  port: 9000

---
## logback config
#logging:
#  config: file:/opt/gateway/logback-spring_pub.xml

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        routes:
          - id: openapi
            uri: http://localhost:${server.port}
            predicates:
              - Path=/v3/api-docs/**
            filters:
              - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

          - id: tuna
            uri: http://localhost:12000/
            predicates:
              - Path=/tuna/**/**
            filters:
              - RewritePath=/tuna/(?<path>.*), /$\{path}

          - id: tunaEclass
            uri: http://localhost:12001/
            predicates:
              - Path=/tunaEclass/**
            filters:
              - RewritePath=/tunaEclass/(?<path>.*), /$\{path}

          - id: tunaLectureApply
            uri: http://localhost:12002/
            predicates:
              - Path=/tunaLectureApply/**
            filters:
              - RewritePath=/tunaLectureApply/(?<path>.*), /$\{path}


