

server:
  port: 12010

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        routes:
          - id: tuna
            uri: http://localhost:12000
            predicates:
              - Path=/tuna/**
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/tuna/(?<path>.*), /$\{path}
          - id: tunaEclass
            uri: http://localhost:12001
            predicates:
              - Path=/tunaEclass/**
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/tunaEclass/(?<path>.*), /$\{path}

          - id: tunaLectureApply
            uri: http://localhost:12002
            predicates:
              - Path=/tunaLectureApply/**
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/tunaLectureApply/(?<path>.*), /$\{path}



